# Generated by Django 4.0.2 on 2022-03-05 08:59

from django.db import migrations, models
import ebook.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=ebook.models.upload_to, verbose_name='Image'),
        ),
    ]
