# Generated by Django 4.0.2 on 2022-03-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Sci Fi'), ('mystery', 'Mystery'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('poetry', 'Poetry'), ('adventure', 'Adventure'), ('drama', 'Drama'), ('nonfiction', 'Nonfiction'), ('media', 'Media'), ('romance', 'Romance'), ('westerns', 'Westerns'), ('action', 'Action'), ('contemporary', 'Contemporary')], default='action', max_length=50, null=True),
        ),
    ]
