# Generated by Django 4.0.2 on 2022-03-12 12:44

from django.db import migrations, models
import ebook.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(default='bookpdf/default.pdf', upload_to=ebook.models.uploadfile_to, verbose_name='pdf'),
        ),
    ]
