# Generated by Django 4.0.2 on 2022-04-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_post_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ISBN',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TrendingBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook.post')),
            ],
        ),
    ]
