# Generated by Django 4.0.2 on 2022-04-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0007_review_postview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isFavorite', models.BooleanField(default=False)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook.post')),
            ],
        ),
    ]
