# Generated by Django 4.0.2 on 2022-03-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_author',
            field=models.BooleanField(auto_created=True, default=False, null=True),
        ),
    ]
